### ISSUE TITLE
Split table cutoff at bottom of page

### ISSUE THREAD

**Issue by lunarcloud** [pagedjs/pagedjs#206]
Using the PagedJS 0.5.0-beta.1 but it happened with the earlier 0.4.x:

Tables seem to occasionally cut off the last row when split across pages.

Normally:
![image](https://github.com/jgm/pandoc/assets/1565970/fa87c855-649f-4179-abc8-d3ac2186ff5c)

If I disable the CSS rule
```css
height: calc(100% - var(--pagedjs-footnotes-height));
```
![image](https://github.com/jgm/pandoc/assets/1565970/afa2bdc7-5e5f-40b4-99c3-9d25292b4dd3)

The blue line is part of my page footer
```css
@page > @bottom-center {
    border-top: 4px solid blue;
}
```

**Comment by lunarcloud** [comment]
Getting rid of the footer 
```css
@footnote {
  display: none;
  height: 0;
}
```
didn't do it

**Comment by julientaq** [comment]
hey there.

do you have any padding/margin bottom on those tr or td or even the table?

**Comment by lunarcloud** [comment]
I have this issue on 2 mostly-the-same templates.

One has some bottom padding:

```css
table {
  margin-bottom: 1em;
}
```

One has no padding or margin specified on the table, tbody, thead, or tr

Both do have tht/td padding
```css
table th,
table td {
    padding: 4px 6px;
}
```

with a 100 lorem ipsum table for content:
```md

| Number | Text                         |
|--------|------------------------------|
| 1      | Lorem ipsum dolor sit amet.  |
| 2      | Lorem ipsum dolor sit amet.  |
| 3      | Lorem ipsum dolor sit amet.  |
| ...    | Lorem ipsum dolor sit amet.  |
| 129    | Lorem ipsum dolor sit amet.  |
```
They will both see the problem, but at different points.

**Comment by julientaq** [comment]
i tried with the latest beta you can get here. and it seems to get better.

<script src="https://unpkg.com/pagedjs@0.5.0-beta.1/dist/paged.polyfill.js"></script>

would you mind testing it?

**Comment by lunarcloud** [comment]
Yes, this has been using the latest beta for the `npm run build` output, but I have now updated the previewer reference used.

[test-pagedjs-206.zip](https://github.com/user-attachments/files/15518113/test-pagedjs-206.zip)

Curiously, the preview looks worse than the PDF - hiding the text before the table.

**Comment by julientaq** [comment]
the cli is not having the latest version of paged.js 

@fchasen  is working on that bit.

**Comment by julientaq** [comment]
oh your css is having a break-inside avoid for everything. You want to remove  that because chrome will make decision where to accept / refuse this rules, and it may break things.

**Comment by julientaq** [comment]
there is some weird things in there 🤔

**Comment by lunarcloud** [comment]
> oh your css is having a break-inside avoid for everything. You want to remove that because chrome will make decision where to accept / refuse this rules, and it may break things.

Noted. Unfortunately removing that rule didn't fix it.

**Comment by julientaq** [comment]
i’m gonna need to check a bit next week as i can’t find the culprit yet

**Comment by julientaq** [comment]
ok so when the button is not there anymore, the 5beta1 all the lines appears.

you can check this file (i made a small hook for the mermaid as i think it would be interesting for you to see how pagedjs can handle those with a bit less hacks): https://gist.github.com/julientaq/84088577c4829b1f4da532439dc53be3

**Comment by julientaq** [comment]
still weird though

**Comment by timbze** [comment]
I "fixed" an issue like this by running this in `afterRendered`
```js
document.querySelector(':root').style.setProperty('--pagedjs-footnotes-height', 'undefined')
```

**Comment by NigelCunningham** [comment]
Please try it with the PR https://github.com/pagedjs/pagedjs/pull/196 - that's working fine for me.

**Comment by julientaq** [comment]
you shouldn’t need to touch the `--pagedjs-footnotes-height` at all, it should be 0 by default if empty. 🤔

**Comment by NigelCunningham** [comment]
Found the issue with this - the code looking for the overflow isn't handling bottom margins perfectly, leading to it returning the wrong element. Hopefully I'll have a fix pretty quickly (today).

**Comment by julientaq** [comment]
awesome, you got me curious. :D

**Comment by NigelCunningham** [comment]
The issue is in firstOverflowingChild. The code needs to better take into account all the fun around margins in order to correctly calculate which child of an element is the start of the overflow. Unfortunately Chrome doesn't make this easy because it gives different numbers to Javascript to what I see in the developer console. Right now, with example code, the bottom table has a height of 391px according to the developer console, but JS (window.getComputedStyle(child).height) says it's 387! So I'm seeking to figure out which number is right and what the cause of the difference is (doesn't seem to be borders or padding right now but I'm yet to try removing them and seeing whether that makes a difference).

Time to make dinner now; I'm aiming to come back to this in a couple of hours.

**Comment by julientaq** [comment]
Does the `element.offsetHeight` give something different? 

That would be a fun thing to test.

**Comment by NigelCunningham** [comment]
Ignoring the differences between the dev console display and JS helps - that just confuses things. Once I stopped worrying about that, everything else makes sense. The last child's top + its height + parent's paddingbottom + parent's borderBottomWidth = parent's bottom measurement

**Comment by NigelCunningham** [comment]
Sorry @julientaq , it's taking longer than anticipated. I'm going to head off to bed and finish it with a fresh mind tomorrow.

**Comment by NigelCunningham** [comment]
#196 has now been updated; please test. Thanks!

**Comment by brendanowens** [comment]
@NigelCunningham I believe this issue with the margins may be affecting more than just tables. I am setting a a value for `--pagedjs-margin-bottom` and occasionally seeing a div dropped between pages upon automatic break. The issue seems to be that pagedJS expects the div to fit on the page, but it just barely does not (usually by only 2 pixels or so).

I am happy to provide more information about the exact situation or open a new issue in the repo. I have confirmed that the issue exists in both 0.4.3 and 0.5.0-beta-1 and the #196 branch's dist polyfill.

> The issue is in firstOverflowingChild. The code needs to better take into account all the fun around margins in order to correctly calculate which child of an element is the start of the overflow. Unfortunately Chrome doesn't make this easy because it gives different numbers to Javascript to what I see in the developer console. Right now, with example code, the bottom table has a height of 391px according to the developer console, but JS (window.getComputedStyle(child).height) says it's 387! So I'm seeking to figure out which number is right and what the cause of the difference is (doesn't seem to be borders or padding right now but I'm yet to try removing them and seeing whether that makes a difference).
> 
> Time to make dinner now; I'm aiming to come back to this in a couple of hours.

**Comment by NigelCunningham** [comment]
Ok. If you can give me HTML that reproduces the issue, I'll be in a better position to debug it. 

Thanks in advance.

**Comment by brendanowens** [comment]
Sure thing -- I will get HTML to reproduce it on Monday as I will need to build a version of it without customer data.

> Ok. If you can give me HTML that reproduces the issue, I'll be in a better position to debug it. Thanks in advance.
> […](#)
> On 9 June 2024 1:06:51 pm AEST, Brendan Owens ***@***.***> wrote: @NigelCunningham I believe this issue with the margins may be affecting more than just tables. I am setting a a value for `--pagedjs-margin-bottom` and occasionally seeing a div dropped between pages upon automatic break. The issue seems to be that pagedJS expects the div to fit on the page, but it just barely does not (usually by only 2 pixels or so). I am happy to provide more information about the exact situation or open a new issue in the repo. I have confirmed that the issue exists in both 0.4.3 and 0.5.0-beta-1 and the #196 branch's dist polyfill. > The issue is in firstOverflowingChild. The code needs to better take into account all the fun around margins in order to correctly calculate which child of an element is the start of the overflow. Unfortunately Chrome doesn't make this easy because it gives different numbers to Javascript to what I see in the developer console. Right now, with example code, the bottom table has a height of 391px according to the developer console, but JS (window.getComputedStyle(child).height) says it's 387! So I'm seeking to figure out which number is right and what the cause of the difference is (doesn't seem to be borders or padding right now but I'm yet to try removing them and seeing whether that makes a difference). > > Time to make dinner now; I'm aiming to come back to this in a couple of hours. -- Reply to this email directly or view it on GitHub: [#206 (comment)](https://github.com/pagedjs/pagedjs/issues/206#issuecomment-2156288842) You are receiving this because you were mentioned. Message ID: ***@***.***>

**Comment by lunarcloud** [comment]
> #196 has now been updated; please test. Thanks!

I tried updating and re-running but still had a hidden row.

What I tried:
```json
{
	"scripts": {
		"build": "npx pagedjs-cli example.html -o example.pdf"
	},
	"devDependencies": {
		"pagedjs-cli": "0.4.3",
		"pagedjs": "github:NigelCunningham/pagedjs#Issue-191"
	},
	"overrides": {
		"pagedjs-cli": {
			"pagedjs": "github:NigelCunningham/pagedjs#Issue-191"
		}
	}
}
```

**Comment by brendanowens** [comment]
@NigelCunningham Here is a minimal reproduction of the issue:

In the file `Doc_onepage.html`, all the content fits on one page, and it works as expected.

In the file `Doc_split`, the div with `data-ref` `f8c96b3e-a197-4b06-9a68-0499413e76e0` has its height increased, which pushes content to a new page. The first bullet point in dropped -- in the DOM it is still included on the first page, but all the way to the upper right corner.

<img width="1746" alt="Screenshot 2024-06-10 at 12 48 41 PM" src="https://github.com/pagedjs/pagedjs/assets/21250577/c7f570c4-56a3-4e04-be77-add24d04b35e">

[page_splitting_issue.zip](https://github.com/user-attachments/files/15777184/page_splitting_issue.zip)

**Comment by brendanowens** [comment]
Upon further testing, this appears to be the issue with `padding-bottom` on the `data-split-to` element. Adding this CSS rule resolved the issue on v0.4.3:

```
[data-split-to] {
  padding-bottom: 0 !important;
  border-bottom: 0 !important;
}
```

It would be nice to have this resolved in 0.5.0, though, so that this custom CSS rule is not needed.

> @NigelCunningham Here is a minimal reproduction of the issue:
> 
> In the file `Doc_onepage.html`, all the content fits on one page, and it works as expected.
> 
> In the file `Doc_split.html`, the div with `data-ref` `f8c96b3e-a197-4b06-9a68-0499413e76e0` has its height increased, which pushes content to a new page. The first bullet point in dropped -- in the DOM it is still included on the first page, but all the way to the upper right corner.
> 
> <img alt="Screenshot 2024-06-10 at 12 48 41 PM" width="1746" src="https://private-user-images.githubusercontent.com/21250577/338290606-c7f570c4-56a3-4e04-be77-add24d04b35e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDgyMjYsIm5iZiI6MTcxODA0NzkyNiwicGF0aCI6Ii8yMTI1MDU3Ny8zMzgyOTA2MDYtYzdmNTcwYzQtNTZhMy00ZTA0LWJlNzctYWRkMjRkMDRiMzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE5MzIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxN2ZhMWEyOWFjZTA1ZTlkNmQxMGMxN2U1ODFlOTFmNGNiNDU0MDNkY2FkYTVlYmQ1OTViZDc0Y2Q3OTQzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._dcXdmk-xmFMLk17xM4SOLo2dUmPqln7L-cO6SN_TBk">
> [page_splitting_issue.zip](https://github.com/user-attachments/files/15777184/page_splitting_issue.zip)

**Comment by julientaq** [comment]
There is already a 

```
.pagedjs_pages > .pagedjs_page > .pagedjs_sheet > .pagedjs_pagebox > .pagedjs_area > div [data-split-to] {
	margin-bottom: unset;
	padding-bottom: unset;
}
```

rule.

Is it possible that you have a css rule that would override it (or another `!important` somewhere?

**Comment by brendanowens** [comment]
@julientaq since there was padding set inline on the HTML element, it was not overwritten by that rule 😕

In out case, the HTML is generated from React, so inline styles are common using the `style` attribute

<img width="801" alt="Screenshot 2024-06-10 at 3 49 54 PM" src="https://github.com/pagedjs/pagedjs/assets/21250577/4b0400f2-2f73-4699-84b4-16921a546c28">

**Comment by NigelCunningham** [comment]
One fix is done - the repeating table headers code needed updating for the fact that the BreakToken structure now includes multiple overflows.

**Comment by julientaq** [comment]
@brendanowens right. i guess we’ll have to add `!important` to our rule then.

**Comment by julientaq** [comment]
note that the selector is not div specific, but will get all the `[data-split-to]` from within the children of the pagearea `<div>`

The problem is that the border, padding-bottom and margin only exist after the page break.

I think that the height of the element should take the possible height of margin/padding/border.

**Comment by NigelCunningham** [comment]
Ah, my bad!

**Comment by NigelCunningham** [comment]
Please retest with the latest pushes for #196. Thanks!

**Comment by lunarcloud** [comment]
> Please try it with the PR #196 - that's working fine for me.

Ensured I was working with the latest commit this time, but got the same results. (my example and result included in attachment)

[test-pagedjs-206.zip](https://github.com/user-attachments/files/15872486/test-pagedjs-206.zip)

**Comment by NigelCunningham** [comment]
Thanks! I'll check again - the working fine for me message was before I made more changes.

**Comment by NigelCunningham** [comment]
I must be being blind, sorry. I can't see anything wrong with the current output - all the rows seem to me to be there. What am I missing, please?

**Comment by lunarcloud** [comment]
> I must be being blind, sorry. I can't see anything wrong with the current output - all the rows seem to me to be there. What am I missing, please?

37 is missing

**Comment by NigelCunningham** [comment]
Hmm, perhaps you'd not running the branch in the PR? I'm seeing 37 at the top of the second page.

![image](https://github.com/pagedjs/pagedjs/assets/107818/4670576e-7c97-48d4-adf2-4a9e87a0886b)

**Comment by NigelCunningham** [comment]
Just checkout the branch in my pull request and build / try that, please.

**Comment by NigelCunningham** [comment]
Any success, @lunarcloud ?

**Comment by lunarcloud** [comment]
I'm so sorry, been flat out on higher priority work (this is still pretty important). Haven't peeled myself away to test this again. But if you're running my example against that new branch successfully, that's looking great

**Comment by NigelCunningham** [comment]
Ok, thanks! Sorry for my lack of patience :)

**Comment by lunarcloud** [comment]
> Just checkout the branch in my pull request and build / try that, please.

I downloaded the branch, built it (`npm run build` and `npm run compile`), but have no idea how to run it against my example html... I'm so sorry to be a newbie - I usually just run the cli against the file.

**Comment by NigelCunningham** [comment]
Hi Sam. 

No stress. I had to learn how to get these things going too.

After building, modify your html so it loads the JD from the dist directory (perhaps copy the file you need elsewhere if that's an option). Another way to proceed is to come an existing test in the specs directory and then run the docker specs npm command, though that does require having docker able to run.

**Comment by lunarcloud** [comment]
Okay, this works in your branch!

![image](https://github.com/pagedjs/pagedjs/assets/1565970/ec41b2c9-a478-4a70-ab71-3c2c17d35547)

**Comment by lunarcloud** [comment]
Excited for when #196 gets merged :D

**Comment by NigelCunningham** [comment]
@julientaq , I've been getting a lot of feedback and have a number of test cases I could still work on, but I'm loosing track of what still needs doing. Could we perhaps merge this PR and make a beta 2, then get people to open new issues for whatever is still in need of attention?

**Comment by julientaq** [comment]
Yes, i’ve been following :D

I believe that yes, we should update the beta to 5b2. 

i’ll get some time soon to check previous works with the beta, to get out ot the beta release. 

@fchasen what do you think?f

**Comment by Petercopter** [comment]
Heya, I've been following along here, and I don't know if this is useful information, or whether it's 100% true yet, but I may have mitigated the 'dropped table row' problem by increasing my footer height.

Using this css
https://github.com/pagedjs/pagedjs/blob/v0.4.3/examples/assets/styles/examples.css

I changed 
```
--pagedjs-margin-bottom: 16mm;
```
to
```
--pagedjs-margin-bottom: 24mm;
```
and it seems like maybe because we had too much content in the footer, that was causing page split problems.

Thanks to everyone involved with Paged.js, looking forward to beta 2!

**Comment by jcace** [comment]
I was having this same issue on v0.4.3, interestingly I was able to resolve it with:

```css
tbody  {
  max-height: 0px; 
} 
```

(the actual value of max-height doesn't seem to matter) 

However after testing out v0.5.0 beta-1, it seems to be resolved and this css rule is no longer needed.

**Comment by Fxlr8** [comment]
> I was having this same issue on v0.4.3, interestingly I was able to resolve it with:
> 
> ```css
> tbody  {
>   max-height: 0px; 
> } 
> ```
> 
> (the actual value of max-height doesn't seem to matter)
> 
> However after testing out v0.5.0 beta-1, it seems to be resolved and this css rule is no longer needed.

This fixed the missing row for me, but introduced another problem. Now one of my tables just cuts off by a page break. It is pretty weird: if there is no content after the table it breaks correctly and renders all the rows. If there is even a small div, it cuts of the table by page break and renders only the div on the next one 🤔

**Comment by Fxlr8** [comment]
> Ignoring the differences between the dev console display and JS helps - that just confuses things. Once I stopped worrying about that, everything else makes sense. The last child's top + its height + parent's paddingbottom + parent's borderBottomWidth = parent's bottom measurement

Have you tried something like [Element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect)? It could be a more reliable way to get the element size and position on the page

**Comment by lunarcloud** [comment]
Can we all stop blowing up my notifications with "I haven't tested this on the PR branch or beta 2 but..." ?
The PR should solve it, i'd close this bug if #196 were merged.

**Comment by Fxlr8** [comment]
> Can we all stop blowing up my notifications with "I haven't tested this on the PR branch or beta 2 but..." ? The PR should solve it, i'd close this bug if #196 were merged.

Could you please point me at "beta 2" branch? I can't seem to find it. Also #196 does not solve the problem completely and still has issues

**Comment by lunarcloud** [comment]
So, @julientaq or maybe @fchasen - does anyone know how I can use the #196 branch with the CLI via NPM?

This does solve the issue I've had AFAIK, but running it via the examples folder isn't going to work in my document build pipeline.
I want to avoid the suggestion someone thrust on me to just "fork it and make your own version" which sounds ill-advised and overkill. 

I tried before to just override the npm config section with git labels, but failed. 

> > #196 has now been updated; please test. Thanks!
> 
> I tried updating and re-running but still had a hidden row.
> 
> What I tried:
> 
> ```json
> {
> 	"scripts": {
> 		"build": "npx pagedjs-cli example.html -o example.pdf"
> 	},
> 	"devDependencies": {
> 		"pagedjs-cli": "0.4.3",
> 		"pagedjs": "github:NigelCunningham/pagedjs#Issue-191"
> 	},
> 	"overrides": {
> 		"pagedjs-cli": {
> 			"pagedjs": "github:NigelCunningham/pagedjs#Issue-191"
> 		}
> 	}
> }
> ```

Not sure what I did wrong.

**Comment by lunarcloud** [comment]
Well, I was able to get it working via

```json
{
	"scripts": {
		"build": "npx pagedjs-cli example.html -o example.pdf"
	},
	"devDependencies": {
		"pagedjs-cli": "^0.5.0-beta.1"
	},
	"overrides": {
		"pagedjs-cli": {
			"pagedjs": "github:NigelCunningham/pagedjs#66286b01dccfb6859d9aaa13fdd7107dc5bc2ff2"
		}
	}
}
```

**Comment by lunarcloud** [comment]
I've opened an issue to deal with the fact that I cannot combine this solution with the beta CLI https://github.com/pagedjs/pagedjs-cli/issues/3 for those interested

**Comment by mediafreakch** [comment]
https://github.com/pagedjs/pagedjs/commit/4cbe30119751cb73d0599b7377f0d8423f2307de fixes our issue with hidden table rows on tables that span multiple pages. Thanks for that 👍🏻  (wonder when `0.5.0-beta.2` will be released?)

However the following [custom paged handler](https://github.com/pagedjs/pagedjs/commit/4cbe30119751cb73d0599b7377f0d8423f2307de) which used to provide **repeated table headers**, stopped working. Any hints on how to fix that would be very welcome.

**Comment by julientaq** [comment]
hey @mediafreakch could you please create a new issue to track it more efficiently? 
thank you!

**Comment by JanScheeleDev** [comment]
Hi.
We have this exact problem too with 0.4.3 and 0.5.0 beta. We are developing on OSX machines with ARM chip where the problem does not occur. On Windows we see the problem with missing rows. Even when running on docker on the windows machine, the problem persists. None of the suggests here did work for us.

What resolves the problem for us (currently) is the following:

.pagedjs_page_content {
    height: calc(10**1**% - var(--pagedjs-footnotes-height)) !important;
}

in your opinion, would this only be a temporal fix for this special case and break other stuff?

Thank you for your help.

**Comment by Fxlr8** [comment]
> We are developing on OSX machines with ARM chip where the problem does not occur

I am developing on OSX with ARM, but those problems still occur. I think OS is not the cause here

**Comment by Fxlr8** [comment]
By the way, if anyone is looking for a quick workaround just stop using table layout. I changed my layout to regular divs with css grid and it works perfectly.

**Comment by lunarcloud** [comment]
This still didn't work for me.
We managed to switch to weasyprint, so I may not follow this bug that closely.

**Comment by jhundley9109** [comment]
Just to add a note here:

I had the same problem and this solved it for me.

    tbody  {
      max-height: 0px;
    }
